import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, GitBranch, RotateCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, SectionHeader, TaskTable } from "@/components/dashboard-ui";
import { DEMO_REQUEST, history } from "@/lib/mock-data";

export const Route = createFileRoute("/history")({ head: () => ({ meta: [{ title: "Workflow History — DataIntel" }, { name: "description", content: "Review workflow versions, adaptive decisions, and prior collection runs." }, { property: "og:title", content: "Workflow History — DataIntel" }, { property: "og:description", content: "Review workflow versions, adaptive decisions, and prior collection runs." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: HistoryPage });

function HistoryPage() { return <div><PageIntro eyebrow="Audit trail" title="Workflow history" description="A complete record of generated blueprints, quality-triggered changes, and collection outcomes." actions={<Button variant="outline"><RotateCw className="size-4" />Rerun workflow</Button>} />
  <div className="grid gap-6 xl:grid-cols-[minmax(0,1.3fr)_minmax(320px,.7fr)]"><section className="border border-border bg-card"><SectionHeader title="Indian SaaS companies hiring Java backend developers" subtitle="DR-1048 · Current workflow version v4" /><div className="border-b border-border bg-muted/30 px-5 py-3"><p className="text-[10px] font-semibold uppercase text-muted-foreground">Original request</p><p className="mt-1 text-xs leading-5">{DEMO_REQUEST}</p></div><div className="p-5">{history.map((item,index) => <div key={item.version} className="relative flex gap-4 pb-7 last:pb-0 after:absolute after:bottom-0 after:left-4 after:top-9 after:w-px after:bg-border last:after:hidden"><span className="z-10 flex size-8 shrink-0 items-center justify-center rounded-full border border-border bg-background text-[11px] font-bold">{item.version}</span><div className="min-w-0 flex-1 border border-border p-4"><div className="flex flex-col justify-between gap-2 sm:flex-row"><div><div className="flex items-center gap-2"><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-semibold">{item.trigger}</span>{index === 0 && <span className="text-[10px] font-semibold text-primary">Current</span>}</div><p className="mt-2 text-sm font-medium">{item.change}</p></div><span className="text-[10px] text-muted-foreground">{item.time}</span></div><div className="mt-3 flex flex-wrap items-center gap-x-4 gap-y-1 border-t border-border pt-3 text-xs"><span className="flex items-center gap-2 text-success"><CheckCircle2 className="size-3.5" />{item.outcome}</span><span className="text-muted-foreground">{item.records}</span><span className="text-muted-foreground">{item.sources} sources</span></div></div></div>)}</div></section>
  <aside className="space-y-6"><section className="border border-border bg-card p-5"><GitBranch className="size-5 text-primary" /><h3 className="mt-4 text-sm font-semibold">Why the workflow changed</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">The platform continuously checks field coverage, duplicates, and agreement between sources. When salary evidence fell below threshold, it added targeted searches instead of guessing values.</p><div className="mt-5 border-t border-border pt-4"><p className="text-[10px] uppercase text-muted-foreground">Net impact this run</p><p className="mt-2 text-2xl font-semibold text-success">+17 pts</p><p className="text-xs text-muted-foreground">Quality score 71 → 88</p></div></section></aside></div>
  <section className="mt-6 border border-border bg-card"><SectionHeader title="All workflow runs" subtitle="Current and previous hiring research requests" /><TaskTable /></section>
  </div>; }
