import { createFileRoute, Link } from "@tanstack/react-router";
import {
  ArrowRight,
  Brain,
  Check,
  Circle,
  Clock3,
  Pause,
  Plus,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro, QualityCallout, SectionHeader, iconForTone } from "@/components/dashboard-ui";
import {
  DEMO_REQUEST,
  interventions,
  understanding as defaultUnderstanding,
  workflowStages as defaultStages,
} from "@/lib/mock-data";
import { cn } from "@/lib/utils";
import { useActiveWorkflowPlan } from "@/lib/workflow-store";

export const Route = createFileRoute("/workflow")({
  head: () => ({
    meta: [
      { title: "Active Workflow — DataIntel" },
      {
        name: "description",
        content:
          "See how the AI understood a request, the generated collection blueprint, and adaptive decisions.",
      },
      { property: "og:title", content: "Active Workflow — DataIntel" },
      {
        property: "og:description",
        content:
          "See how the AI understood a request, the generated collection blueprint, and adaptive decisions.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: WorkflowPage,
});

export function WorkflowPage() {
  const plan = useActiveWorkflowPlan();

  const title = plan ? plan.title : "Indian SaaS companies hiring Java backend developers";
  const eyebrow = plan ? `Running · ${plan.id}` : "Running · DR-1048";
  const description = plan ? plan.request : DEMO_REQUEST;

  const understandingItems: [string, string][] = plan
    ? [
        ["Objective", plan.understanding.objective],
        ["Target", plan.understanding.target],
        ["Geography", plan.understanding.geography],
        ["Industry", plan.understanding.industry],
        [
          "Constraints",
          Array.isArray(plan.understanding.constraints)
            ? plan.understanding.constraints.join("; ")
            : String(plan.understanding.constraints ?? "—"),
        ],
        [
          "Required fields",
          Array.isArray(plan.understanding.requiredFields)
            ? plan.understanding.requiredFields.join(", ")
            : String(plan.understanding.requiredFields ?? "—"),
        ],
        ["Freshness", plan.understanding.freshness],
        ["Search intent", plan.understanding.searchIntent],
      ]
    : (defaultUnderstanding as unknown as [string, string][]);

  const stages = plan ? plan.stages : defaultStages;
  const blueprintSubtitle = plan
    ? `${plan.stages.length}-step workflow generated by Gemini for this request`
    : "8-step workflow generated by the AI for this request";

  return (
    <div>
      <PageIntro
        eyebrow={eyebrow}
        title={title}
        description={description}
        actions={
          <>
            <Link to="/requests">
              <Button variant="outline">
                <Plus className="size-4" />
                New request
              </Button>
            </Link>
            <Button variant="outline">
              <Pause className="size-4" />
              Pause
            </Button>
            <Button variant="outline">
              <RotateCcw className="size-4" />
              Restart
            </Button>
          </>
        }
      />

      <div className="mb-6 grid gap-4 sm:grid-cols-4">
        {[
          ["Progress", plan ? "15%" : "82%"],
          ["Records", plan ? "Planning" : "47 → 36 unique"],
          ["Quality score", plan ? "Evaluating" : "88 / 100"],
          ["Elapsed", plan ? "Just now" : "29m 06s"],
        ].map(([label, value]) => (
          <div className="border border-border bg-card p-4" key={label}>
            <p className="text-[11px] font-medium text-muted-foreground">{label}</p>
            <p className="mt-2 text-xl font-semibold tabular-nums">{value}</p>
          </div>
        ))}
      </div>

      <section className="mb-6 border border-border bg-card">
        <SectionHeader
          title="AI understanding"
          subtitle={
            plan
              ? "Live Gemini breakdown of your natural-language requirements"
              : "How the request was interpreted before any data was collected"
          }
          action={
            <div className="flex items-center gap-1.5 text-xs text-primary font-medium">
              {plan && <Sparkles className="size-3.5" />}
              <Brain className="size-4" />
            </div>
          }
        />
        <dl className="grid gap-px bg-border sm:grid-cols-2 lg:grid-cols-4">
          {understandingItems.map(([k, v]) => (
            <div key={k} className="bg-card px-5 py-3.5">
              <dt className="text-[10px] font-semibold uppercase text-muted-foreground">{k}</dt>
              <dd className="mt-1 text-xs font-medium leading-5">{v}</dd>
            </div>
          ))}
        </dl>
      </section>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.35fr)_minmax(340px,.65fr)]">
        <div className="space-y-6">
          <section className="border border-border bg-card">
            <SectionHeader title="Collection blueprint" subtitle={blueprintSubtitle} />
            <div className="px-5 py-2">
              {stages.map((stage, index) => (
                <div
                  key={`${stage.name}-${index}`}
                  className="relative flex gap-4 py-4 after:absolute after:bottom-0 after:left-[15px] after:top-10 after:w-px after:bg-border last:after:hidden"
                >
                  <span
                    className={cn(
                      "z-10 flex size-8 shrink-0 items-center justify-center rounded-full border text-[11px] font-semibold",
                      stage.status === "complete" &&
                        "border-success bg-success text-success-foreground",
                      stage.status === "active" && "border-primary bg-primary-muted text-primary",
                      stage.status === "pending" &&
                        "border-border bg-background text-muted-foreground",
                    )}
                  >
                    {stage.status === "complete" ? (
                      <Check className="size-4" />
                    ) : stage.status === "active" ? (
                      <span className="size-2 animate-pulse rounded-full bg-primary" />
                    ) : (
                      <Circle className="size-3" />
                    )}
                  </span>
                  <div className="flex min-w-0 flex-1 items-center justify-between gap-4">
                    <div>
                      <p className="text-sm font-medium">
                        <span className="mr-1.5 text-muted-foreground">{index + 1}.</span>
                        {stage.name}
                      </p>
                      <p className="mt-0.5 text-xs text-muted-foreground">{stage.detail}</p>
                    </div>
                    <span className="text-xs font-semibold tabular-nums text-muted-foreground">
                      {stage.count}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <QualityCallout />
        </div>

        <aside className="space-y-6">
          <section className="border border-border bg-card">
            <SectionHeader
              title="Adaptive decisions"
              subtitle="Live changes made by the workflow"
            />
            <div className="p-5">
              {interventions.map((item) => {
                const Icon = iconForTone(item.tone);
                return (
                  <div key={item.title} className="relative flex gap-3 pb-6 last:pb-0">
                    <Icon
                      className={cn(
                        "mt-0.5 size-4 shrink-0",
                        item.tone === "success"
                          ? "text-success"
                          : item.tone === "warning"
                            ? "text-warning"
                            : "text-primary",
                      )}
                    />
                    <div>
                      <div className="flex items-center gap-2">
                        <p className="text-xs font-semibold">{item.title}</p>
                        <span className="text-[10px] tabular-nums text-muted-foreground">
                          {item.time}
                        </span>
                      </div>
                      <p className="mt-1 text-xs leading-5 text-muted-foreground">{item.detail}</p>
                    </div>
                  </div>
                );
              })}
              <div className="mt-2 border-t border-border pt-4">
                <p className="text-[10px] uppercase text-muted-foreground">
                  Salary evidence coverage
                </p>
                <div className="mt-2 flex items-center gap-3">
                  <span className="text-sm font-semibold text-warning">42%</span>
                  <div className="relative h-2 flex-1 rounded-full bg-muted">
                    <div className="absolute inset-y-0 left-0 w-[78%] rounded-full bg-success/40" />
                    <div className="absolute inset-y-0 left-0 w-[42%] rounded-full bg-success" />
                  </div>
                  <span className="text-sm font-semibold text-success">78%</span>
                </div>
              </div>
            </div>
          </section>

          <section className="border border-border bg-card p-5">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-xs text-muted-foreground">Validated records ready to inspect</p>
                <p className="mt-1 text-2xl font-semibold">31</p>
              </div>
              <Clock3 className="size-5 text-primary" />
            </div>
            <Link
              to="/datasets"
              className="mt-5 flex items-center justify-between border-t border-border pt-4 text-xs font-semibold text-primary"
            >
              Open live dataset <ArrowRight className="size-4" />
            </Link>
          </section>
        </aside>
      </div>
    </div>
  );
}
